[package]
name = "server"
version = "0.1.0"
authors = ["Marcin <kociolek.farfocle@gmail.com>"]


[dependencies]
getopts = "^0.2"
hyper = "^0.7"
rustc-serialize = "^0.3"
log = "^0.3"
yaml-rust = "^0.3"
clippy = {version = "*", optional = true}
openssl = "^0.7"
hyperlocal = "^0.1"
libc = "^0"

[dependencies.jsonrpc]
git = "https://bitbucket.org/kociolek/jsonrpc.git"

[dependencies.syslog]
git = "https://bitbucket.org/kociolek/rust-syslog.git"

[features]
default = []
dev = ["clippy"]
