[package]
name = "server"
version = "0.1.0"
authors = ["Marcin <kociolek.farfocle@gmail.com>"]


[dependencies]
getopts = "^0.2"
hyper = "^0.7"
rustc-serialize = "^0.3"
log = "^0.3"
yaml-rust = "^0.3"
clippy = {version = "*", optional = true}
rust-crypto = "^0.2"
hyperlocal = "^0.1"

[dependencies.jsonrpc]
git = "https://kociolek@bitbucket.org/kociolek/jsonrpc.git"
branch = "custom-properties"

[features]
default = []
dev = ["clippy"]
