[package]
name = "server"
version = "0.1.0"
authors = ["Marcin <kociolek.farfocle@gmail.com>"]


[dependencies]
hyper = "*"
rustc-serialize = "*"
log = "*"
yaml-rust = "*"
regex = "*"
clippy = {version = "*", optional = true}
rust-crypto = "*"
hyperlocal = "0.1.0"

[dependencies.jsonrpc]
git = "https://kociolek@bitbucket.org/kociolek/jsonrpc.git"
branch = "custom-properties"

[dependencies.clap]
version = "*"
features = [ "yaml" ]

[features]
default = []
dev = ["clippy"]
