[package]

name = "server"

version = "0.1.0"

authors = ["Marcin <kociolek.farfocle@gmail.com>"]


[dependencies]
hyper = "*"
rustc-serialize = "*"
log = "0.3.2"
yaml-rust = "0.2.2"
regex = "0.1.41"

# https://bitbucket.org/kociolek/jsonrpc/
[dependencies.jsonrpc]
path = "jsonrpc"

[dependencies.clap]
version = "1.3.0"
features = [ "yaml" ]
