[package]
name = "server"
version = "0.1.0"
authors = ["Marcin <kociolek.farfocle@gmail.com>"]


[dependencies]
serde="*"
serde_json="*"
hyper = "*"
rustc-serialize = "*"
log = "0.3.2"
yaml-rust = "0.2.2"
regex = "0.1.41"
clippy = {version = "0.0.21", optional = true}
rust-crypto = "0.2.34"

[dependencies.jsonrpc]
git = "https://kociolek@bitbucket.org/kociolek/jsonrpc.git"

[dependencies.clap]
version = "1.3.0"
features = [ "yaml" ]

[features]
default = []
dev = ["clippy"]
