name: jsonrpcd
version: 1.0
about: Simple JSON-RPCd with streaming support
author: Marcin K. <mkocot@k.pl>

settings: 
    - ArgRequiredElseHelp

# All Args must be defined in the 'args:' list where the name of the arg, is the
# key to a Hash object
args:
    - config:
        long: config
        help: Set config file
        takes_value: true
